### ISSUE TITLE
Trocar  Texto

### ISSUE THREAD

**Issue by Silva-17** [CityConnectBr/leadpage-gasbrasiliano#1]
Trocar to texto _Para participar, basta acessar o link abaixo e acompanhar pelo Youtube no dia 22/10, às 16h00_ para  `Participe da Live no dia 22/10 às 16h00 e acompanhe o que há de mais novo no setor.`

![image](https://user-images.githubusercontent.com/42952431/94573431-76dc9300-0248-11eb-8da6-fc79d99cbd9a.png)

**Comment by fabio-pv** [comment]
@Silva-17 Atualizar a produção
